// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APIForHetfield;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Hetfield.Models;

public partial class CarColor : DbModelBase
{
    public int IdCarColors { get; set; }

    public string ColorName { get; set; }

    public string Hex { get; set; }

    [JsonIgnore]
    public virtual ICollection<CarsPassport> CarsPassports { get; set; } = new List<CarsPassport>();

    public override async Task<bool> Validate(bool addMode)
    {
        string message = string.Empty;
        if (this == null)
        {
            message = "Ошибка определения типа";
        }
        if (ColorName.Length == 0)
        {
            message = "Поля не заполнены";
        }
        if (ColorName.Length > 50)
        {
            message = "Назване цвета не может быть больше 50 символов";
        }
        if(Hex.Length == 0)
        {
            message = "Цвет не выбран";
        }
        ApiClient apiClient = new ApiClient();
        if (await apiClient.GetAllEntityData<CarColor>() is IEnumerable<CarColor> carColors && carColors.Any(cc => cc.ColorName == ColorName || cc.Hex == Hex) && addMode)
        {
            message = "Такая запись уже есть в базе";
        }
        return message != string.Empty ? ValidateResult(message) : true;
    }

    public override string ToString()
    {
        return ColorName + " " + Hex;
    }
}