// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APIForHetfield;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Hetfield.Models;

public partial class CarType : DbModelBase
{
    public int IdCarType { get; set; }

    public string TypeName { get; set; }

    [JsonIgnore]
    public virtual ICollection<CarsPassport> CarsPassports { get; set; } = new List<CarsPassport>();

    public override async Task<bool> Validate(bool addMode)
    {
        string message = string.Empty;
        if (this == null)
        {
            message = "Ошибка определения типа";
        }
        if (TypeName.Length == 0)
        {
            message = "Поля не заполнены";
        }
        if (TypeName.Length > 25)
        {
            message = "Тип автомобиля не может быть больше 25 символов";
        }
        ApiClient apiClient = new ApiClient();
        if (await apiClient.GetAllEntityData<CarType>() is IEnumerable<CarType> carTypes && carTypes.Any(cc => cc.TypeName == this.TypeName) && addMode)
        {
            message = "Такая запись уже есть в базе";
        }
        return message != string.Empty ? ValidateResult(message) : true;
    }

    public override string ToString()
    {
        return TypeName;
    }
}