// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APIForHetfield;
using Hetfield.View;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Hetfield.Models;

public partial class Gender : DbModelBase
{
    public int IdGender { get; set; }

    public string GenderName { get; set; }

    [JsonIgnore]
    public virtual ICollection<User> Users { get; set; } = new List<User>();


    public override async Task<bool> Validate(bool addmode)
    {
        string message = string.Empty;
        if (this == null)
        {
            message = "Ошибка определения типа";
        }
        if (GenderName.Length == 0)
        {
            message = "Поля не заполнены";
        }
        if(GenderName.Length > 7)
        {
            message = "Назване пола не может быть больше 7 символов";
        }
        ApiClient apiClient = new ApiClient();
        if (await apiClient.GetAllEntityData<Gender>() is IEnumerable<Gender> genders && genders.Any(g => g.GenderName == GenderName) && addmode)
        {
            message = "Такая запись уже есть в базе";
        }
        if (message != string.Empty)
        {
            return ValidateResult(message);
        }
        else
        {
            return true;
        }

    }



    public override string ToString()
    {
        return GenderName;
    }
}