// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APIForHetfield;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Media;

namespace Hetfield.Models;

public partial class ManufactureYear : DbModelBase
{
    public int YearValue { get; set; }

    public virtual ICollection<CarsPassport> CarsPassports { get; set; } = new List<CarsPassport>();

    public override async Task<bool> Validate(bool addMode)
    {
        string message = string.Empty;
        if (this == null)
        {
            message = "Ошибка определения типа";
        }
        if (YearValue > 1900)
        {
            message = "Год производства отсчитывается с 1900 года";
        }
        if (YearValue <= DateTime.Now.Year)
        {
            message = "Год, который вы пытаетесь добавить еще не наступил";
        }
        ApiClient apiClient = new ApiClient();
        if (await apiClient.GetAllEntityData<ManufactureYear>() is IEnumerable<ManufactureYear> manufactureYears && manufactureYears.Any(cc => cc.YearValue == this.YearValue) && addMode)
        {
            message = "Такая запись уже есть в базе";
        }
        return message != string.Empty ? ValidateResult(message) : true;
    }

    public override string ToString()
    {
        return YearValue.ToString();
    }
}