// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APIForHetfield;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using System.Windows.Media;

namespace Hetfield.Models;

public partial class OrderStatus : DbModelBase
{
    public int IdOrderStatus { get; set; }

    public string OrderStatusName { get; set; }

    [JsonIgnore]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public override async Task<bool> Validate(bool addMode)
    {
        string message = string.Empty;
        if (this == null)
        {
            message = "Ошибка определения типа";
        }
        if (OrderStatusName.Length == 0)
        {
            message = "Поля не заполнены";
        }
        if (OrderStatusName.Length > 20)
        {
            message = "Статус заказа не может быть больше 25 символов";
        }
        ApiClient apiClient = new ApiClient();
        if (await apiClient.GetAllEntityData<OrderStatus>() is IEnumerable<OrderStatus> orderStatus && orderStatus.Any(cc => cc.OrderStatusName == this.OrderStatusName) && addMode)
        {
            message = "Такая запись уже есть в базе";
        }
        return message != string.Empty ? ValidateResult(message) : true;
    }

    public override string ToString()
    {
        return OrderStatusName;
    }
}