// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using APIForHetfield;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Hetfield.Models;

public partial class Role : DbModelBase
{
    public int IdRole { get; set; }

    public string RoleName { get; set; }


    [JsonIgnore]
    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public override async Task<bool> Validate(bool addMode)
    {
        string message = string.Empty;
        if (this == null)
        {
            message = "Ошибка определения типа";
        }
        if (RoleName.Length == 0)
        {
            message = "Поля не заполнены";
        }
        if (RoleName.Length > 25)
        {
            message = "Роль не может быть больше 25 символов";
        }
        ApiClient apiClient = new ApiClient();
        if (await apiClient.GetAllEntityData<Role>() is IEnumerable<Role> role && role.Any(cc => cc.RoleName == this.RoleName) && addMode)
        {
            message = "Такая запись уже есть в базе";
        }
        return message != string.Empty ? ValidateResult(message) : true;
    }

    public override string ToString()
    {
        return RoleName;
    }
}