// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIForHetfield.Models;

public partial class ManufactureYear
{
    public int YearValue { get; set; }

    public virtual ICollection<CarsPassport> CarsPassports { get; set; } = new List<CarsPassport>();

    public override string ToString() => Convert.ToString(YearValue);
}