// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace APIForHetfield.Models;

public partial class User
{
    public int IdUser { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public byte[] Photo { get; set; }

    public int IdRole { get; set; }

    public int IdGender { get; set; }

    [JsonIgnore]
    public virtual ICollection<CarsPassport> CarsPassports { get; set; } = new List<CarsPassport>();

    public virtual Gender IdGenderNavigation { get; set; }

    public virtual Role IdRoleNavigation { get; set; }

    [JsonIgnore]
    public virtual ICollection<Order> OrderIdBuyerNavigations { get; set; } = new List<Order>();
    [JsonIgnore]
    public virtual ICollection<Order> OrderIdStaffNavigations { get; set; } = new List<Order>();

    public override string ToString()
    {
        return this.Surname + " " +
                this.Name + " " +
                this.Patronymic + " " +
                $"{this.DateOfBirth:d}" + " " +
                this.PhoneNumber + " " +
                this.Email + " " +
                this.Login + " " +
                this.Password + " " +
                this.IdRoleNavigation.RoleName + " " +
                this.IdGenderNavigation.GenderName;
    }
}